### ISSUE TITLE
MobileBroadbandAccount can't be used with Python?

### ISSUE THREAD

**Issue by DODRO35** [microsoft/xlang#660] opened 2020-06-25 18:32 UTC
I'm attempting to use MobileBroadbandAccount Class but I can't get it to work!
I saw this message on the Microsoft doc: 

```
This functionality is only available to mobile operator apps and UWP apps given privileged access by mobile network operators.
```
Does that mean it's impossible to use this class with Python at all?

**Comment by jonwis** [comment] 2020-06-25 20:58
What does "can't get it to work" mean here? Like, the Python projection doesn't run? Or you get an error trying to use the functionality?  APIs guarded by capabilities will usually return `E_ACCESS_DENIED` (`0x80070005`) indicating that your application doesn't have access.  See the [list of app capabilities](https://docs.microsoft.com/en-us/uwp/api/windows.networking.networkoperators.mobilebroadbandaccount?view=winrt-19041) for how to request access.  Once your app has the appropriate capability you should be able to use it from Python.

**Comment by DODRO35** [comment] 2020-06-25 22:05
> What does "can't get it to work" mean here? Like, the Python projection doesn't run? Or you get an error trying to use the functionality? 

When I use MobileBroadbandAccount.get_available_network_account_ids() it returns an empty IVectorView. But when I use the same method in a universal Windows app in c# it contains the network account id from my device.

Furthermore, if I try to use MobileBroadbandAccount.create_from_network_account_id(accountId) with the account ID retrieved from the c# app I get the following error

```Python
Traceback (most recent call last):
  File "C:\Users\Dominic\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\201.7223.92\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\Dominic\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\201.7223.92\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Dominic/Desktop/test_repo/test.py", line 9, in <module>
    mobileBroadbandAccount = MobileBroadbandAccount.create_from_network_account_id(accountId)
RuntimeError: Error initializing the MobileBroadbandAccount object.
```

**Comment by DODRO35** [comment] 2020-06-26 13:46
Am I doing something wrong?

**Comment by KevinTXY** [comment] 2020-06-26 16:56
@Scottj1s This is the same issue I mentioned earlier, I think he's having troubles working around packaging his work.
I've played with it myself and it seems trying to add a reference to a Python solution is blocked because Python solutions are not considered executables. Checking the "Windows Application" box in the Python solution's properties tab doesn't make it any more possible though. I assume that some kind of hosted app that can deliver the Python script needs to be made in this case?

**Comment by DODRO35** [comment] 2020-06-26 20:27
I just want a solution to give my python script those capabilities ... 
```XAML
<rescap:Capability Name="cellularDeviceIdentity"/>
<rescap:Capability Name="cellularDeviceControl"/>
<rescap:Capability Name="cellularMessaging" />
```
I searching and trying many things but can't get it to work ...

**Comment by kennykerr** [comment] 2020-06-29 21:14
I'm sorry Dominic, I don't know the first thing about Python. 

@BenJKuhn can speak to whether we have someone working on Python that can help. 

@jonwis do you still need to declare capabilities if the code is running outside an app container? I don't know how the Python code is hosted, but perhaps that would unblock this example.

**Comment by jonwis** [comment] 2020-06-29 21:40
Some APIs require their callers to be packaged and use the appropriate capabilities.  For now you can [grant your executable identity](https://blogs.windows.com/windowsdeveloper/2019/10/29/identity-registration-and-activation-of-non-packaged-win32-apps/) and see if that moves the ball forward.

**Comment by DODRO35** [comment] 2020-06-30 00:37
> Some APIs require their callers to be packaged and use the appropriate capabilities. For now you can [grant your executable identity](https://blogs.windows.com/windowsdeveloper/2019/10/29/identity-registration-and-activation-of-non-packaged-win32-apps/) and see if that moves the ball forward.

I tried this but it seems AddPackageByUriAsync method is available starting in Windows 10, version 2004. And I don't have this version yet it's not yet available in my setting ...

**Comment by DODRO35** [comment] 2020-06-30 02:04
> Some APIs require their callers to be packaged and use the appropriate capabilities. For now you can [grant your executable identity](https://blogs.windows.com/windowsdeveloper/2019/10/29/identity-registration-and-activation-of-non-packaged-win32-apps/) and see if that moves the ball forward.

I tried this but I can't use `AddPackageByUriAsync` method because it is available starting in Windows 10, version 2004 and I can't update to windows 10, version 2004 yet it seems ...

![image](https://user-images.githubusercontent.com/54362191/86074475-09a44080-ba54-11ea-92fd-e17858398ded.png)

**Comment by DODRO35** [comment] 2020-06-30 17:29
@jonwis 
> APIs guarded by capabilities will usually return `E_ACCESS_DENIED` (`0x80070005`) indicating that your application doesn't have access. 

Reading the doc I found this, [MobileBroadbandAccount.AvailableNetworkAccountIds returns an empty list](https://docs.microsoft.com/en-us/windows-hardware/drivers/mobilebroadband/create-a-mobilebroadbandaccount-object#mobilebroadbandaccountavailablenetworkaccountids-returns-an-empty-list) it says that if the app is not trusted I'll receive an empty list just like I have

**Comment by jonwis** [comment] 2020-06-30 19:27
Ok, then "everything is working as designed."  Your app asked for the set of IDs and got back the empty-list, meaning "there are no available account IDs for your app."  Passing a broadband account ID from one app to the API in another app fails by design - the ID isn't available to the second app.  Our API design patterns say that methods with a name like `Create...` _fail_ if they can't create the thing they were asked to.

Asking around I found that this family of APIs does have a requirement that it be called from an AppContainer (UWP app) with the mobile broadband capability.

Depending on what you're trying to do, you _could_ set up a UWP like this with an [app service entrypoint](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appservice?view=winrt-19041), deploy that, then interact with the app service from your python code to be a "proxy."  Not a great answer, though.

**Comment by DODRO35** [comment] 2020-06-30 19:39
okay... I'll see what I can do with that. Thanks for your help

**Comment by BenJKuhn** [comment] 2021-02-20 05:27
Closing this out as the issue appears to be understood, and is an API / usage issue, rather than an issue with the projection support itself.

**Closed by BenJKuhn** 2021-02-20 05:27 UTC
