### ISSUE TITLE
Enable Undocked Regfree WinRT to work on Win8.1 and Win7

### ISSUE THREAD

**Issue by AdamBraden** [microsoft/xlang#687] opened 2020-08-12 01:25 UTC
The detours library that enables undocked regfree winrt could in theory work down to Win7 - take a closer look to see if this is possible - for both Win8.1 and Win7. 

Win8.1 currently errors with Error 0x8007109A – This operation is only valid in the context of an app container.

Win7 fails to load the component - possibly due to api set issues.

**Comment by kythant** [comment] 2020-10-16 18:07
Windows 8.1
0x8007109A error is caused by the app container check that exists in windows 8.1 but not on later versions.
This can be fixed by, setting the linker option of your component that you're activating to /APPCONTAINER:NO
https://docs.microsoft.com/en-us/cpp/build/reference/appcontainer-windows-store-app?view=vs-2019
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/windows-app-certification-kit-tests#appcontainercheck

Windows 7
Because the RoAPIs are missing on windows 7 and the project is based on detouring, it does not seem worthwhile to design a whole new version of the project just for win7 once you take into account that there is no customer demand for win7 support.

**Closed** 2020-10-16 21:06 UTC
Labels: feature
