### ISSUE TITLE
Python/winrt: can't import winrt in jupyter notebook: 无法在设置线程模式后对其加以更改

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/xlang#757] opened 2021-09-01 05:24 UTC
![image](https://user-images.githubusercontent.com/54425948/131616475-a48ed29a-a294-45f8-9e71-c410c8254f80.png)

**Comment by dlech** [comment] 2021-09-01 13:50
Translation of error: "Cannot change thread mode after setting it"

This sounds like a duplicate of #690. 

Here is a potential workaround:

```python
from winrt import _winrt

_winrt.uninit_apartment()
```

**Comment by oxygen-dioxide** [comment] 2021-09-05 01:04
Your code doesn't work for me
![image](https://user-images.githubusercontent.com/54425948/132111594-d289fe71-7f08-4c47-8aa9-aef736358e46.png)

However, if I use importlib.import, it works.
 ```py
import importlib
_winrt=importlib.import_module("winrt._winrt")
_winrt.uninit_apartment()
```

**Closed** 2023-03-03 01:41 UTC
Labels: no-issue-activity
