### ISSUE TITLE
Python/winrt installation issue

### ISSUE THREAD

**Issue by pbvinoth** [microsoft/xlang#675] opened 2020-07-07 06:16 UTC
I was trying to install the python/winrt module but facing error like 

C:\Users\vpbx\Desktop>pip install winrt
**ERROR: Could not find a version that satisfies the requirement winrt (from versions: none)
ERROR: No matching distribution found for winrt**

https://pypi.org/project/winrt/

My all Prerequisites are satisfied but still facing the error.
    Windows 10, October 2018 Update or later.
    Python for Windows, version 3.7 or later
    pip, version 19 or later

please help here

**Comment by sahikon** [comment] 2020-07-11 23:28
Looks like duplicate of #634

**Comment by BenJKuhn** [comment] 2020-08-26 18:01
Yes, this is a duplicate, closing.

**Closed by BenJKuhn** 2020-08-26 18:01 UTC
