### ISSUE TITLE
The winrt package is not available for Python v3.10

### ISSUE THREAD

**Issue by aakash-sahai** [microsoft/xlang#791] opened 2023-05-25 21:41 UTC
Any plans to relase the winrt Python packager for Python v3.10?

**Comment by dlech** [comment] 2023-05-25 21:43
Duplicate of #763. Project has moved to https://github.com/pywinrt/python-winsdk which has been released for 3.10 and 3.11.

**Closed** 2023-06-02 18:42 UTC
