### ISSUE TITLE
I had a problem using winrt.windows.graphics.capture!

### ISSUE THREAD

**Issue by Lookforworld** [microsoft/xlang#756] opened 2021-07-28 14:44 UTC
My code like this:

> 

        from winrt.windows.graphics.capture import GraphicsCapturePicker 
        async def get_item():
            picker =  GraphicsCapturePicker()
            item = await picker.pick_single_item_async()
            return item

        

When I want to use get_item(), it doesn't pop up any window for me to select something!
Am I using it wrong? @dlech

**Comment by TheBlackPlague** [comment] 2021-07-31 12:48
To add on to this issue, it seems that `Direct3D11CaptureFramePool` has no method called `Create()` meaning the `Windows.Graphics.Capture` namespace seems to have not been implemented correctly/completely. 

Is there any work happening in regards to this or could you possibly provide any insight on this issue? @dlech

**Comment by TheBlackPlague** [comment] 2021-07-31 13:30
@Lookforworld Are you running 'get_item()`? If so, how?

**Comment by TheBlackPlague** [comment] 2021-07-31 13:51
To expand on this issue, `GraphicsCapturePicker().pick_single_item_async()` throws a `RuntimeError`.

Reproduction Code:
```py
import asyncio

from winrt.windows.graphics.capture import Direct3D11CaptureFramePool, Direct3D11CaptureFrame, GraphicsCaptureSession, \
    GraphicsCaptureItem, GraphicsCapturePicker

if not GraphicsCaptureSession.is_supported():
    print('Not supported.')
else:
    print('Supported.')


async def getGraphicsCaptureItem():
    print('I ran.')
    picker: GraphicsCapturePicker = GraphicsCapturePicker()
    item: GraphicsCaptureItem = await picker.pick_single_item_async()
    print('I ran.')
    print(item)

asyncio.run(getGraphicsCaptureItem())
```

Is there possibly going to be a fix for this?

**Comment by dlech** [comment] 2021-07-31 13:58
I don't know anything about these APIs or how they are supposed to be used, but if you use [one of my builds](https://github.com/dlech/xlang/actions/runs/996674046), it should give a more descriptive `OSError` instead of a `RuntimeError` that may help narrow down the problem.

**Comment by TheBlackPlague** [comment] 2021-08-01 08:53
> I don't know anything about these APIs or how they are supposed to be used, but if you use [one of my builds](https://github.com/dlech/xlang/actions/runs/996674046), it should give a more descriptive `OSError` instead of a `RuntimeError` that may help narrow down the problem.

Sorry if I'm mistaken, but aren't your builds failing? That's what I see according to the CI. 🤔

**Comment by Lookforworld** [comment] 2021-08-01 11:24
> I don't know anything about these APIs or how they are supposed to be used, but if you use [one of my builds](https://github.com/dlech/xlang/actions/runs/996674046), it should give a more descriptive `OSError` instead of a `RuntimeError` that may help narrow down the problem.

Still no ideas......My head is buzzing！I have read the official documents for countless times and still can't find the problem!

**Comment by TheBlackPlague** [comment] 2021-08-01 12:08
> > I don't know anything about these APIs or how they are supposed to be used, but if you use [one of my builds](https://github.com/dlech/xlang/actions/runs/996674046), it should give a more descriptive `OSError` instead of a `RuntimeError` that may help narrow down the problem.
> 
> Still no ideas......My head is buzzing！I have read the official documents for countless times and still can't find the problem!

I'm pretty sure the issue is the lack of response from the API is the way we're using it in Python. 

@dlech I think you're better to investigate this issue as per my analysis, it is caused by a lack of property setting I believe.

As per: [Microsoft's Docs](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture#add-the-screen-capture-capability), there needs to be a property set called "Graphics Capture" as indicated in the application manifest. I believe that's causing the Runtime error as Windows doesn't believe the Python application should have such capability to request it. Maybe have Python/WinRT set it? 

Please let me know once you've reviewed. The documents further show how the API is meant to be used (if you want to understand).

**Comment by TheBlackPlague** [comment] 2021-08-04 12:31
Checking to see if any progress is made regarding this issue. Please do share any information you have (even if they're temporary fixes).

**Comment by madtatu-development** [comment] 2021-10-01 20:40
Hi, may I ask if you found any solution ?

I am trying to make a simple code working, doing nothing else just capturing a window based on its HWND (without picker), but I could not make it work, most probably, because I am dummie. 

Any help would be VERY much appreciated.

**Comment by sakurasoooo** [comment] 2022-01-22 11:35
I encountered the same problem. I think the picker need to be initialize with a handle of new window, [GraphicsCapturePicker Constructor](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturepicker.-ctor?view=winrt-22000#windows-graphics-capture-graphicscapturepicker-ctor) and [IInitializeWithWindow::Initialize method](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-iinitializewithwindow-initialize)
but IInitializeWithWindow interface is not implemented in any python libraries. 
Can anyone fix the picker so that it can be initialized with a hwnd?

**Comment by dlech** [comment] 2022-01-22 15:35
Nice find. I guess we could implement a [helper method like C#](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api?tabs=csharp#classes-that-use-iinitializewithwindow)

```python
from winrt._winrt import intialize_with_window

picker = GraphicsPicker()
intialize_with_window(picker, tkinter_window.winfo_id())
...
```

Or if we can detect this interface in the WinRT metadata, we could have the bindings generator create a `Self.with_hwnd(hwnd: int) -> Self`method that could be used in a chained sort of way: 

```python
picker = GraphicsCapturePicker().with_hwnd(tkinter_window.winfo_id())
...
```

**Comment by dlech** [comment] 2022-01-22 17:24
I just pushed a fix to my branch. Tested working with:

```python
import turtle

from winrt._winrt import initialize_with_window
from winrt.windows.foundation import IAsyncOperation, AsyncStatus
from winrt.windows.graphics.capture import GraphicsCapturePicker, GraphicsCaptureItem

def on_pick_completed(op: IAsyncOperation, status: AsyncStatus) -> None:
    if status == AsyncStatus.ERROR:
        print("error: ", status.error_code.value)
    elif status == AsyncStatus.CANCELED:
        # this is programatically, canceled, not user canceled
        print("operation canceled")
    elif status == AsyncStatus.COMPLETED:
        result: Optional[GraphicsCaptureItem] = op.get_results()
        if result:
            print("result:",  result.display_name)
        else:
            print("user canceled")

    op.close()

picker = GraphicsCapturePicker()
initialize_with_window(picker, turtle.getcanvas().winfo_id())
op = picker.pick_single_item_async()
op.completed = on_pick_completed

turtle.mainloop()
```

It can be uses with async/await of course, but this was a quick hack to test it using only the standard library.

**Comment by sakurasoooo** [comment] 2022-01-23 00:26
> I just pushed a fix to my branch. Tested working with:
> 
> ```python
> import turtle
> 
> from winrt._winrt import initialize_with_window
> from winrt.windows.foundation import IAsyncOperation, AsyncStatus
> from winrt.windows.graphics.capture import GraphicsCapturePicker, GraphicsCaptureItem
> 
> def on_pick_completed(op: IAsyncOperation, status: AsyncStatus) -> None:
>     if status == AsyncStatus.ERROR:
>         print("error: ", status.error_code.value)
>     elif status == AsyncStatus.CANCELED:
>         # this is programatically, canceled, not user canceled
>         print("operation canceled")
>     elif status == AsyncStatus.COMPLETED:
>         result: Optional[GraphicsCaptureItem] = op.get_results()
>         if result:
>             print("result:",  result.display_name)
>         else:
>             print("user canceled")
> 
>     op.close()
> 
> picker = GraphicsCapturePicker()
> initialize_with_window(picker, turtle.getcanvas().winfo_id())
> op = picker.pick_single_item_async()
> op.completed = on_pick_completed
> 
> turtle.mainloop()
> ```
> 
> It can be used with async/await of course, but this was a quick hack to test it using only the standard library.

It works, thanks, at least it pops up the picker dialogs.

**Comment by dlech** [comment] 2022-05-30 15:08
Please try [winsdk](https://pypi.org/project/winsdk/) instead of [winrt](https://pypi.org/project/winrt/).

**Comment by BruceZhang1993** [comment] 2022-05-31 01:25
> Please try [winsdk](https://pypi.org/project/winsdk/) instead of [winrt](https://pypi.org/project/winrt/).

It works. Thanks a lot :)

**Closed** 2023-03-03 01:41 UTC
Labels: no-issue-activity

**Comment by wookidooki8** [comment] 2023-11-05 23:30
> Please try [winsdk](https://pypi.org/project/winsdk/) instead of [winrt](https://pypi.org/project/winrt/).
```

import turtle

from winsdk._winrt import initialize_with_window
from winsdk.windows.foundation import IAsyncOperation, AsyncStatus
from winsdk.windows.graphics.capture import GraphicsCapturePicker, GraphicsCaptureItem

def on_pick_completed(op: IAsyncOperation, status: AsyncStatus) -> None:
    if status == AsyncStatus.ERROR:
        print("error: ", status.error_code.value)
    elif status == AsyncStatus.CANCELED:
        # this is programatically, canceled, not user canceled
        print("operation canceled")
    elif status == AsyncStatus.COMPLETED:
        result: Optional[GraphicsCaptureItem] = op.get_results()
        if result:
            print("result:",  result.display_name)
        else:
            print("user canceled")

    op.close()

picker = GraphicsCapturePicker()
initialize_with_window(picker, turtle.getcanvas().winfo_id())
op = picker.pick_single_item_async()
op.completed = on_pick_completed

turtle.mainloop()
```


When I applied the above code, the window selection screen appears, but after selecting the window I want to capture, nothing is displayed on the screen. Is there a way to resolve this issue?
